/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as ALPHTradeContractJson } from "../ALPHTrade.ral.json";
import { getContractByCodeHash } from "./contracts";
import { OracleValue, AllStructs } from "./types";

// Custom types for the contract
export namespace ALPHTradeTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
    usdcId: HexString;
    balance: bigint;
    liquidity: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    balance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getUsdcId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getLpId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    deposit: {
      params: CallContractParams<{ usdcAmount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ lpAmount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    balance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUsdcId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getLpId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{ usdcAmount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ lpAmount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  ALPHTradeInstance,
  ALPHTradeTypes.Fields
> {
  encodeFields(fields: ALPHTradeTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): ALPHTradeInstance {
    return new ALPHTradeInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    balance: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "balance", params, getContractByCodeHash);
    },
    getUsdcId: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getUsdcId", params, getContractByCodeHash);
    },
    getLpId: async (
      params: Omit<
        TestContractParamsWithoutMaps<ALPHTradeTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getLpId", params, getContractByCodeHash);
    },
    deposit: async (
      params: TestContractParamsWithoutMaps<
        ALPHTradeTypes.Fields,
        { usdcAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        ALPHTradeTypes.Fields,
        { lpAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const ALPHTrade = new Factory(
  Contract.fromJson(
    ALPHTradeContractJson,
    "",
    "0d9954ab0d50ea80c73491531163b77f3f562e4797dfab8cd0ec60fb3c6949e5",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class ALPHTradeInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ALPHTradeTypes.State> {
    return fetchContractState(ALPHTrade, this);
  }

  view = {
    getSymbol: async (
      params?: ALPHTradeTypes.CallMethodParams<"getSymbol">
    ): Promise<ALPHTradeTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        ALPHTrade,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: ALPHTradeTypes.CallMethodParams<"getName">
    ): Promise<ALPHTradeTypes.CallMethodResult<"getName">> => {
      return callMethod(
        ALPHTrade,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: ALPHTradeTypes.CallMethodParams<"getDecimals">
    ): Promise<ALPHTradeTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        ALPHTrade,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: ALPHTradeTypes.CallMethodParams<"getTotalSupply">
    ): Promise<ALPHTradeTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        ALPHTrade,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    balance: async (
      params?: ALPHTradeTypes.CallMethodParams<"balance">
    ): Promise<ALPHTradeTypes.CallMethodResult<"balance">> => {
      return callMethod(
        ALPHTrade,
        this,
        "balance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUsdcId: async (
      params?: ALPHTradeTypes.CallMethodParams<"getUsdcId">
    ): Promise<ALPHTradeTypes.CallMethodResult<"getUsdcId">> => {
      return callMethod(
        ALPHTrade,
        this,
        "getUsdcId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getLpId: async (
      params?: ALPHTradeTypes.CallMethodParams<"getLpId">
    ): Promise<ALPHTradeTypes.CallMethodResult<"getLpId">> => {
      return callMethod(
        ALPHTrade,
        this,
        "getLpId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: ALPHTradeTypes.CallMethodParams<"deposit">
    ): Promise<ALPHTradeTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        ALPHTrade,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: ALPHTradeTypes.CallMethodParams<"withdraw">
    ): Promise<ALPHTradeTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        ALPHTrade,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(ALPHTrade, this, "getSymbol", params);
    },
    getName: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"getName">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(ALPHTrade, this, "getName", params);
    },
    getDecimals: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(ALPHTrade, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(ALPHTrade, this, "getTotalSupply", params);
    },
    balance: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"balance">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"balance">> => {
      return signExecuteMethod(ALPHTrade, this, "balance", params);
    },
    getUsdcId: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"getUsdcId">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"getUsdcId">> => {
      return signExecuteMethod(ALPHTrade, this, "getUsdcId", params);
    },
    getLpId: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"getLpId">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"getLpId">> => {
      return signExecuteMethod(ALPHTrade, this, "getLpId", params);
    },
    deposit: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"deposit">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(ALPHTrade, this, "deposit", params);
    },
    withdraw: async (
      params: ALPHTradeTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<ALPHTradeTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(ALPHTrade, this, "withdraw", params);
    },
  };

  async multicall<Callss extends ALPHTradeTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<ALPHTradeTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      ALPHTrade,
      this,
      callss,
      getContractByCodeHash
    )) as ALPHTradeTypes.MulticallReturnType<Callss>;
  }
}
