/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as SetValueScriptJson } from "../scripts/SetValue.ral.json";
import { default as WithdrawScriptJson } from "../scripts/Withdraw.ral.json";
import { OracleValue, AllStructs } from "./types";

export const SetValue = new ExecutableScript<{
  oracle: HexString;
  key: HexString;
  value: bigint;
}>(Script.fromJson(SetValueScriptJson, "", AllStructs), getContractByCodeHash);

export const Withdraw = new ExecutableScript<{
  token: HexString;
  amount: bigint;
}>(Script.fromJson(WithdrawScriptJson, "", AllStructs), getContractByCodeHash);
