/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct } from "@alephium/web3";
import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));
export interface OracleValue extends Record<string, Val> {
  value: bigint;
  timestamp: bigint;
}
export interface Position extends Record<string, Val> {
  owner: Address;
  market: HexString;
  type: bigint;
  colateral: bigint;
  leverage: bigint;
  entryPrice: bigint;
  entryTimestamp: bigint;
}
